# Generated by Django 5.1 on 2024-08-28 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('director', models.CharField(max_length=300)),
                ('genre', models.CharField(max_length=300)),
                ('release_year', models.IntegerField()),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('personal_notes', models.TextField(blank=True)),
                ('watched', models.BooleanField(default=False)),
            ],
        ),
    ]
